# H2 Console (데이터베이스 관리 화면) 활성화
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Source (데이터베이스 연결 정보)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Settings (데이터베이스 자동 관리 설정)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true